---
apiVersion: v1
kind: Namespace
metadata:
  name: telco
  labels:
    app.kubernetes.io/managed-by: kubectl
    istio-injection: enabled
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: telco-config
  namespace: telco
data:
  KAFKA_BROKERS: "kafka-0.kafka:9092,kafka-1.kafka:9092,kafka-2.kafka:9092"
  REDIS_ADDR: "redis-master.telco:6379"
  TOPIC_CALL_EVENTS: "call-events"
  TOPIC_CDR: "cdr-events"
  TOPIC_ORCH_EVENTS: "orchestrator-events"
  TOPIC_ROUTING_REQ: "routing-requests"
  TOPIC_ROUTING_DECISIONS: "routing-decisions"
  TOPIC_RECORDING_CTRL: "recording-control"
  TOPIC_TRANSCRIPTIONS: "transcription-events"
  LOG_LEVEL: "info"
---
apiVersion: v1
kind: Secret
metadata:
  name: telco-secrets
  namespace: telco
type: Opaque
stringData:
  REDIS_PASSWORD: ""
  AWS_ACCESS_KEY_ID: ""
  AWS_SECRET_ACCESS_KEY: ""
  CRM_API_KEY: ""
  GOOGLE_APPLICATION_CREDENTIALS_JSON: ""
  DATABASE_URL: "postgresql://telco:CHANGE_ME@postgres:5432/telco_analytics"
